import scipy.stats as scst
import matplotlib.pyplot as plt

Nadist=scst.norm(loc=4,scale=1)
Nbdist=scst.norm(loc=8,scale=2)

#A
points=[5,6,7]
for p in points:
    print(p,"most likely generatd by "+("Na" if Nadist.pdf(p)> Nbdist.pdf(p) else "Nb")+" distibution")

#B
minX=1
maxX=14
step=0.1
pointsNa=[]
pointsNb=[]
pointsx=[]
for x in (minX+i*step for i in range(int((maxX-minX)/step))):
    pointsx.append(x)
    pointsNa.append(Nadist.pdf(x))
    pointsNb.append(Nbdist.pdf(x))
plt.plot(pointsx,pointsNa)
plt.plot(pointsx,pointsNb)
plt.show()

xst=5
xed=6
step=0.01
delta=1
resx=0
for x in (i*step+xst for i in range(int((xed-xst)/step))):
    d=abs(Nadist.pdf(x)-Nbdist.pdf(x))
    if d<delta:
        delta,resx=d,x
print(resx,"can be generated by both distributions with equal probability") 